#define YY_toy_plus_plus_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from ./Source/grammar.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "./Source/grammar.y"

    /*
    statements are collapsed to the left side of grammar
    */

    // set up stage before writing the language grammar
    #include<bits/stdc++.h>
    #include "../Includes/combined_includes.hpp"
    using namespace std;

    // root node to start printing the ast
    // any value assigning to any field of Node here causes does not name a type error
    Node* root = new Node();

    // global symbol table
    symbol_table* table = new symbol_table();

    // define yyerror here which is filled by bison later 
    int yyerror(string s);

    // define yylex here which is filled by bison later
    // define them here because they are copied later in the header
    // these funcitons are supplied to other files by grammar.h or extern keyword
    int yylex();
    int yyparse();

#line 32 "./Source/grammar.y"
typedef union {
    Node* node;
} yy_toy_plus_plus_stype;
#define YY_toy_plus_plus_STYPE yy_toy_plus_plus_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_toy_plus_plus_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_toy_plus_plus_BISON 1

#ifndef YY_toy_plus_plus_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_toy_plus_plus_COMPATIBILITY 1
 #else
  #define  YY_toy_plus_plus_COMPATIBILITY 0
 #endif
#endif

#if YY_toy_plus_plus_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_toy_plus_plus_LTYPE
   #define YY_toy_plus_plus_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_toy_plus_plus_STYPE 
   #define YY_toy_plus_plus_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_toy_plus_plus_DEBUG
   #define  YY_toy_plus_plus_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_toy_plus_plus_USE_GOTO
  #define YY_toy_plus_plus_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_toy_plus_plus_USE_GOTO
 #define YY_toy_plus_plus_USE_GOTO 0
#endif

#ifndef YY_toy_plus_plus_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_toy_plus_plus_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_toy_plus_plus_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"
#define YY_toy_plus_plus_DEBUG 1

#line 136 "/usr/share/bison++/bison.cc"
/* YY_toy_plus_plus_DEBUG */
#endif


#ifndef YY_toy_plus_plus_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_toy_plus_plus_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_toy_plus_plus_LSP_NEEDED
#ifndef YY_toy_plus_plus_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_toy_plus_plus_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_toy_plus_plus_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_toy_plus_plus_STYPE
#define YY_toy_plus_plus_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_toy_plus_plus_PARSE
#define YY_toy_plus_plus_PARSE yyparse
#endif
#ifndef YY_toy_plus_plus_LEX
#define YY_toy_plus_plus_LEX yylex
#endif
#ifndef YY_toy_plus_plus_LVAL
#define YY_toy_plus_plus_LVAL yylval
#endif
#ifndef YY_toy_plus_plus_LLOC
#define YY_toy_plus_plus_LLOC yylloc
#endif
#ifndef YY_toy_plus_plus_CHAR
#define YY_toy_plus_plus_CHAR yychar
#endif
#ifndef YY_toy_plus_plus_NERRS
#define YY_toy_plus_plus_NERRS yynerrs
#endif
#ifndef YY_toy_plus_plus_DEBUG_FLAG
#define YY_toy_plus_plus_DEBUG_FLAG yydebug
#endif
#ifndef YY_toy_plus_plus_ERROR
#define YY_toy_plus_plus_ERROR yyerror
#endif

#ifndef YY_toy_plus_plus_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_toy_plus_plus_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_toy_plus_plus_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_toy_plus_plus_PARSE_PARAM
  #define YY_toy_plus_plus_PARSE_PARAM void
 #endif
#endif

#if YY_toy_plus_plus_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_toy_plus_plus_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_toy_plus_plus_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_toy_plus_plus_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_toy_plus_plus_PURE
#  ifndef YYPURE
#    define YYPURE YY_toy_plus_plus_PURE
#  endif
#endif

#ifdef YY_toy_plus_plus_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_toy_plus_plus_DEBUG 
#  endif
#endif

#ifndef YY_toy_plus_plus_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_toy_plus_plus_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_toy_plus_plus_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_toy_plus_plus_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	INT	258
#define	FLOAT	259
#define	FUNCTION	260
#define	VOID	261
#define	VALUE	262
#define	RETURN	263


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_toy_plus_plus_CLASS
#define YY_toy_plus_plus_CLASS toy_plus_plus
#endif
#ifndef YY_toy_plus_plus_INHERIT
#define YY_toy_plus_plus_INHERIT
#endif
#ifndef YY_toy_plus_plus_MEMBERS
#define YY_toy_plus_plus_MEMBERS 
#endif
#ifndef YY_toy_plus_plus_LEX_BODY
#define YY_toy_plus_plus_LEX_BODY  
#endif
#ifndef YY_toy_plus_plus_ERROR_BODY
#define YY_toy_plus_plus_ERROR_BODY  
#endif
#ifndef YY_toy_plus_plus_CONSTRUCTOR_PARAM
#define YY_toy_plus_plus_CONSTRUCTOR_PARAM
#endif
#ifndef YY_toy_plus_plus_CONSTRUCTOR_CODE
#define YY_toy_plus_plus_CONSTRUCTOR_CODE
#endif
#ifndef YY_toy_plus_plus_CONSTRUCTOR_INIT
#define YY_toy_plus_plus_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_toy_plus_plus_USE_CONST_TOKEN
#define YY_toy_plus_plus_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_toy_plus_plus_USE_CONST_TOKEN != 0
#ifndef YY_toy_plus_plus_ENUM_TOKEN
#define YY_toy_plus_plus_ENUM_TOKEN yy_toy_plus_plus_enum_token
#endif
#endif

class YY_toy_plus_plus_CLASS YY_toy_plus_plus_INHERIT
{
public: 
#if YY_toy_plus_plus_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int INT;
static const int FLOAT;
static const int FUNCTION;
static const int VOID;
static const int VALUE;
static const int RETURN;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_toy_plus_plus_ENUM_TOKEN { YY_toy_plus_plus_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,INT=258
	,FLOAT=259
	,FUNCTION=260
	,VOID=261
	,VALUE=262
	,RETURN=263


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_toy_plus_plus_PARSE (YY_toy_plus_plus_PARSE_PARAM);
 virtual void YY_toy_plus_plus_ERROR(char *msg) YY_toy_plus_plus_ERROR_BODY;
#ifdef YY_toy_plus_plus_PURE
#ifdef YY_toy_plus_plus_LSP_NEEDED
 virtual int  YY_toy_plus_plus_LEX (YY_toy_plus_plus_STYPE *YY_toy_plus_plus_LVAL,YY_toy_plus_plus_LTYPE *YY_toy_plus_plus_LLOC) YY_toy_plus_plus_LEX_BODY;
#else
 virtual int  YY_toy_plus_plus_LEX (YY_toy_plus_plus_STYPE *YY_toy_plus_plus_LVAL) YY_toy_plus_plus_LEX_BODY;
#endif
#else
 virtual int YY_toy_plus_plus_LEX() YY_toy_plus_plus_LEX_BODY;
 YY_toy_plus_plus_STYPE YY_toy_plus_plus_LVAL;
#ifdef YY_toy_plus_plus_LSP_NEEDED
 YY_toy_plus_plus_LTYPE YY_toy_plus_plus_LLOC;
#endif
 int   YY_toy_plus_plus_NERRS;
 int    YY_toy_plus_plus_CHAR;
#endif
#if YY_toy_plus_plus_DEBUG != 0
 int YY_toy_plus_plus_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_toy_plus_plus_CLASS(YY_toy_plus_plus_CONSTRUCTOR_PARAM);
public:
 YY_toy_plus_plus_MEMBERS 
};
/* other declare folow */
#if YY_toy_plus_plus_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_toy_plus_plus_CLASS::INT=258;
const int YY_toy_plus_plus_CLASS::FLOAT=259;
const int YY_toy_plus_plus_CLASS::FUNCTION=260;
const int YY_toy_plus_plus_CLASS::VOID=261;
const int YY_toy_plus_plus_CLASS::VALUE=262;
const int YY_toy_plus_plus_CLASS::RETURN=263;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_toy_plus_plus_CLASS::token */
#endif
/*apres const  */
YY_toy_plus_plus_CLASS::YY_toy_plus_plus_CLASS(YY_toy_plus_plus_CONSTRUCTOR_PARAM) YY_toy_plus_plus_CONSTRUCTOR_INIT
{
#if YY_toy_plus_plus_DEBUG != 0
YY_toy_plus_plus_DEBUG_FLAG=0;
#endif
YY_toy_plus_plus_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		49
#define	YYFLAG		-32768
#define	YYNTBASE	20

#define YYTRANSLATE(x) ((unsigned)(x) <= 263 ? yytranslate[x] : 32)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    14,
    15,    11,     9,    19,    10,     2,    12,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    18,     2,
    13,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    16,     2,    17,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8
};

#if YY_toy_plus_plus_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     7,    10,    15,    17,    19,    21,    24,
    28,    31,    34,    37,    40,    43,    46,    49,    52,    55,
    59,    63,    65,    69,    73,    75,    79
};

static const short yyrhs[] = {    21,
     0,    21,    22,     0,    22,     0,    23,    27,     0,     5,
    24,    25,     7,     0,     3,     0,     4,     0,     6,     0,
    25,    15,     0,    25,    19,    26,     0,    14,    26,     0,
    14,    15,     0,    24,     7,     0,    27,    17,     0,    27,
    28,     0,    16,    28,     0,    31,    18,     0,    30,    18,
     0,     8,    18,     0,    29,    11,     7,     0,    29,    12,
     7,     0,     7,     0,    30,     9,    29,     0,    30,    10,
    29,     0,    29,     0,    26,    13,    30,     0,     7,    13,
    30,     0
};

#endif

#if (YY_toy_plus_plus_DEBUG != 0) || defined(YY_toy_plus_plus_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    63,    73,    82,    91,   100,   124,   131,   138,   146,   154,
   162,   170,   179,   199,   209,   217,   226,   234,   242,   251,
   271,   294,   312,   326,   338,   349,   364
};

static const char * const yytname[] = {   "$","error","$illegal.","INT","FLOAT",
"FUNCTION","VOID","VALUE","RETURN","'+'","'-'","'*'","'/'","'='","'('","')'",
"'{'","'}'","';'","','","end_point_of_collapse","list_of_functions","function",
"function_declaration","data_type","arguement_list_with_brackets","variable_declaration",
"compound_statement_with_brackets","statement_with_semicolon","multiplicative_statement",
"additive_statement","assignment_statement",""
};
#endif

static const short yyr1[] = {     0,
    20,    21,    21,    22,    23,    24,    24,    24,    25,    25,
    25,    25,    26,    27,    27,    27,    28,    28,    28,    29,
    29,    29,    30,    30,    30,    31,    31
};

static const short yyr2[] = {     0,
     1,     2,     1,     2,     4,     1,     1,     1,     2,     3,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     3,
     3,     1,     3,     3,     1,     3,     3
};

static const short yydefact[] = {     0,
     0,     1,     3,     0,     6,     7,     8,     0,     2,     0,
     4,     0,     0,    22,     0,     0,     0,    16,    25,     0,
     0,    14,    15,    12,    11,     5,     9,     0,     0,    19,
    13,     0,     0,     0,     0,     0,    18,    17,    10,    22,
    27,    26,    20,    21,    23,    24,     0,     0,     0
};

static const short yydefgoto[] = {    47,
     2,     3,     4,    16,    13,    17,    11,    18,    19,    20,
    21
};

static const short yypact[] = {    15,
     8,    15,-32768,   -13,-32768,-32768,-32768,    -1,-32768,    21,
    -2,     4,     2,     5,    14,    19,    28,-32768,    23,    13,
    22,-32768,-32768,-32768,-32768,-32768,-32768,     8,    35,-32768,
-32768,    35,    36,    37,    35,    35,-32768,-32768,-32768,-32768,
    27,    27,-32768,-32768,    23,    23,    45,    46,-32768
};

static const short yypgoto[] = {-32768,
-32768,    47,-32768,    49,-32768,   -12,-32768,    40,     3,     1,
-32768
};


#define	YYLAST		51


static const short yytable[] = {    25,
     5,     6,    10,     7,    14,    15,     5,     6,    26,     7,
     5,     6,    12,     7,    22,    39,    27,    29,    24,     1,
    28,    35,    36,     5,     6,    31,     7,    14,    15,    41,
    37,    30,    42,    33,    34,    35,    36,    45,    46,    38,
    32,    40,    43,    44,    48,    49,     0,     0,     9,     8,
    23
};

static const short yycheck[] = {    12,
     3,     4,    16,     6,     7,     8,     3,     4,     7,     6,
     3,     4,    14,     6,    17,    28,    15,    13,    15,     5,
    19,     9,    10,     3,     4,     7,     6,     7,     8,    29,
    18,    18,    32,    11,    12,     9,    10,    35,    36,    18,
    13,     7,     7,     7,     0,     0,    -1,    -1,     2,     1,
    11
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_toy_plus_plus_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_toy_plus_plus_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_toy_plus_plus_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_toy_plus_plus_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_toy_plus_plus_CHAR = (token), YY_toy_plus_plus_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_toy_plus_plus_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_toy_plus_plus_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_toy_plus_plus_PURE
/* UNPURE */
#define YYLEX           YY_toy_plus_plus_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_toy_plus_plus_CHAR;                      /*  the lookahead symbol        */
YY_toy_plus_plus_STYPE      YY_toy_plus_plus_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_toy_plus_plus_NERRS;                 /*  number of parse errors so far */
#ifdef YY_toy_plus_plus_LSP_NEEDED
YY_toy_plus_plus_LTYPE YY_toy_plus_plus_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_toy_plus_plus_LSP_NEEDED
#define YYLEX           YY_toy_plus_plus_LEX(&YY_toy_plus_plus_LVAL, &YY_toy_plus_plus_LLOC)
#else
#define YYLEX           YY_toy_plus_plus_LEX(&YY_toy_plus_plus_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_toy_plus_plus_DEBUG != 0
int YY_toy_plus_plus_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_toy_plus_plus_CLASS::
#endif
     YY_toy_plus_plus_PARSE(YY_toy_plus_plus_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_toy_plus_plus_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_toy_plus_plus_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_toy_plus_plus_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_toy_plus_plus_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_toy_plus_plus_LSP_NEEDED
  YY_toy_plus_plus_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_toy_plus_plus_LTYPE *yyls = yylsa;
  YY_toy_plus_plus_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_toy_plus_plus_PURE
  int YY_toy_plus_plus_CHAR;
  YY_toy_plus_plus_STYPE YY_toy_plus_plus_LVAL;
  int YY_toy_plus_plus_NERRS;
#ifdef YY_toy_plus_plus_LSP_NEEDED
  YY_toy_plus_plus_LTYPE YY_toy_plus_plus_LLOC;
#endif
#endif

  YY_toy_plus_plus_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_toy_plus_plus_DEBUG != 0
  if (YY_toy_plus_plus_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_toy_plus_plus_NERRS = 0;
  YY_toy_plus_plus_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_toy_plus_plus_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_toy_plus_plus_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_toy_plus_plus_LSP_NEEDED
      YY_toy_plus_plus_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_toy_plus_plus_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_toy_plus_plus_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_toy_plus_plus_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_toy_plus_plus_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_toy_plus_plus_LSP_NEEDED
      yyls = (YY_toy_plus_plus_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_toy_plus_plus_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_toy_plus_plus_DEBUG != 0
      if (YY_toy_plus_plus_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_toy_plus_plus_DEBUG != 0
  if (YY_toy_plus_plus_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_toy_plus_plus_CHAR == YYEMPTY)
    {
#if YY_toy_plus_plus_DEBUG != 0
      if (YY_toy_plus_plus_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_toy_plus_plus_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_toy_plus_plus_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_toy_plus_plus_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_toy_plus_plus_DEBUG != 0
      if (YY_toy_plus_plus_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_toy_plus_plus_CHAR);

#if YY_toy_plus_plus_DEBUG != 0
      if (YY_toy_plus_plus_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_toy_plus_plus_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_toy_plus_plus_CHAR, YY_toy_plus_plus_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_toy_plus_plus_DEBUG != 0
  if (YY_toy_plus_plus_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_toy_plus_plus_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_toy_plus_plus_CHAR != YYEOF)
    YY_toy_plus_plus_CHAR = YYEMPTY;

  *++yyvsp = YY_toy_plus_plus_LVAL;
#ifdef YY_toy_plus_plus_LSP_NEEDED
  *++yylsp = YY_toy_plus_plus_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_toy_plus_plus_DEBUG != 0
  if (YY_toy_plus_plus_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 64 "./Source/grammar.y"
{
        // doing this in upper c++ code creates does not name a type error
        root->ast = new ast_node("start");
        root->ast->addChildren(1, yyvsp[0].node->ast);
        
        //pcout << "collapse to end_point_of_collapse\n";
    ;
    break;}
case 2:
#line 74 "./Source/grammar.y"
{
        yyval.node = new Node();
        yyval.node->ast = yyvsp[-1].node->ast;
        yyval.node->ast->addChildren(1, yyvsp[0].node->ast);
        
        //pcout << "collect in list_of_function\n";
    ;
    break;}
case 3:
#line 83 "./Source/grammar.y"
{
        yyval.node = new Node();
        yyval.node->ast = new ast_node("list_of_functions", 1, yyvsp[0].node->ast);
        
        //pcout << "collapse to list_of_functions\n";
    ;
    break;}
case 4:
#line 92 "./Source/grammar.y"
{
        yyval.node = new Node();
        yyval.node->ast = new ast_node("function", 2, yyvsp[-1].node->ast, yyvsp[0].node->ast);
        
        //pcout << "collapse to function\n";
    ;
    break;}
case 5:
#line 101 "./Source/grammar.y"
{
        yyval.node = new Node();

        // building ast
        yyval.node->ast = new ast_node("function_declaration", 3, yyvsp[-3].node->ast, yyvsp[-2].node->ast, yyvsp[-1].node->ast, yyvsp[0].node->ast);
        
        // type checking
        if(table->find(yyvsp[0].node->ast->name)) {
            cout << "\033[31mERROR\033[0m: this variable already exist with another type." << endl;
        }
        else {
            table->table[yyvsp[0].node->ast->name] = yyvsp[-3].node->type;
        }
        // switch the table here because compound statement opens after a statement collapses
        symbol_table* child_table = new symbol_table();
        child_table->parent_table = table;
        table->children_tables.push_back(child_table);
        table = child_table;
        
        //pcout << "collapse to function_declaration\n";
    ;
    break;}
case 6:
#line 125 "./Source/grammar.y"
{
        yyval.node = yyvsp[0].node;
        
        //pcout << "collapse to data_type\n";
    ;
    break;}
case 7:
#line 132 "./Source/grammar.y"
{
        yyval.node = yyvsp[0].node;
        
        //pcout << "collapse to data_type\n";
    ;
    break;}
case 8:
#line 139 "./Source/grammar.y"
{
        yyval.node = yyvsp[0].node;
        
        //pcout << "collapse to data_type\n";
    ;
    break;}
case 9:
#line 147 "./Source/grammar.y"
{
        yyval.node = yyvsp[-1].node;
        yyval.node->ast->addChildren(1, yyvsp[0].node->ast);

        //pcout << "end collecting arguement_list_with_brackets\n";
    ;
    break;}
case 10:
#line 155 "./Source/grammar.y"
{
        yyval.node = yyvsp[-2].node;
        yyval.node->ast->addChildren(2, yyvsp[-1].node->ast, yyvsp[0].node->ast);
        
        //pcout << "collect in arguement_list_with_brackets\n";
    ;
    break;}
case 11:
#line 163 "./Source/grammar.y"
{
        yyval.node = new Node();
        yyval.node->ast = new ast_node("arguement_list_with_brackets", 2, yyvsp[-1].node->ast, yyvsp[0].node->ast);
        
        //pcout << "collapse to arguement_list_with_brackets\n";
    ;
    break;}
case 12:
#line 171 "./Source/grammar.y"
{
        yyval.node = new Node();
        yyval.node->ast = new ast_node("arguement_list_with_brackets", 2, yyvsp[-1].node->ast, yyvsp[0].node->ast);
        
        //pcout << "collapse empty arguement_list_with_brackets\n"
    ;
    break;}
case 13:
#line 180 "./Source/grammar.y"
{
        yyval.node = new Node();
        yyval.node->ast = new ast_node("variable_declaration", 2, yyvsp[-1].node->ast, yyvsp[0].node->ast);

        yyval.node->type = yyvsp[-1].node->type;
        if(yyvsp[0].node->type != DATA_TYPE::_VARIABLE) {
            cout << "\033[31mERROR\033[0m: use valid variable name." << endl;
        }
        else if(table->find(yyvsp[0].node->ast->name)) {
            cout << "\033[31mERROR\033[0m: this variable already exist with another type." << endl;
        }
        else {
            table->table[yyvsp[0].node->ast->name] = yyvsp[-1].node->type;
        }
        
        //pcout << "collapse to variable_declaration\n";
    ;
    break;}
case 14:
#line 200 "./Source/grammar.y"
{
        yyval.node = yyvsp[-1].node;
        yyval.node->ast->addChildren(1, yyvsp[0].node->ast);

        table = table->parent_table;
        
        //pcout << "end collecting compound_statements_with_brackets\n";
    ;
    break;}
case 15:
#line 210 "./Source/grammar.y"
{
        yyval.node = yyvsp[-1].node;
        yyval.node->ast->addChildren(1, yyvsp[0].node->ast);
        
        //pcout << "collect in compound_statement_with_brackets\n";
    ;
    break;}
case 16:
#line 218 "./Source/grammar.y"
{
        yyval.node = new Node();
        yyval.node->ast = new ast_node("compound_statement_with_brackets", 2, yyvsp[-1].node->ast, yyvsp[0].node->ast);
        
        //pcout << "collapse to compound_statement_with_brackets\n";
    ;
    break;}
case 17:
#line 227 "./Source/grammar.y"
{
        yyval.node = new Node();
        yyval.node->ast = new ast_node("statement_with_semicolon", 2, yyvsp[-1].node->ast, yyvsp[0].node->ast);
        
        //pcout << "collapse to statement_with_semicolon\n";
    ;
    break;}
case 18:
#line 235 "./Source/grammar.y"
{
        yyval.node = new Node();
        yyval.node->ast = new ast_node("statement_with_semicolon", 2, yyvsp[-1].node->ast, yyvsp[0].node->ast);
        
        //pcout << "collapse to statement_with_semicolon\n";
    ;
    break;}
case 19:
#line 243 "./Source/grammar.y"
{
        yyval.node = new Node();
        yyval.node->ast = new ast_node("statement_with_semicolon", 2, yyvsp[-1].node->ast, yyvsp[0].node->ast);
        
        //pcout << "collapse return statement\n";
    ;
    break;}
case 20:
#line 252 "./Source/grammar.y"
{
        yyval.node = yyvsp[-2].node;
        yyval.node->ast->addChildren(2, yyvsp[-1].node->ast, yyvsp[0].node->ast);

        if(yyvsp[0].node->type == DATA_TYPE::_VARIABLE) {
            if(table->find(yyvsp[-2].node->ast->name)) {
                yyval.node->type = table->table[yyvsp[0].node->ast->name];
            }
            else {
                cout << "\033[31mERROR\033[0m: variable \"" << yyvsp[0].node->ast->name << "\" does not exist." << endl;
            }
        }
        if(yyvsp[-2].node->type != yyvsp[0].node->type) {
            cout << "\033[31mERROR\033[0m: type mismatch in multiplication." << endl;
        }
        
        //pcout << "collect multiplication\n";
    ;
    break;}
case 21:
#line 272 "./Source/grammar.y"
{
        yyval.node = yyvsp[-2].node;
        yyval.node->ast->addChildren(2, yyvsp[-1].node->ast, yyvsp[0].node->ast);

        if(yyvsp[0].node->type == DATA_TYPE::_VARIABLE) {
            if(table->find(yyvsp[0].node->ast->name)) {
                yyval.node->type = table->table[yyvsp[0].node->ast->name];
            }
            else {
                cout << "\033[31mERROR\033[0m: variable \"" << yyvsp[-2].node->ast->name << "\" does not exist." << endl;
            }
        }
        if(yyvsp[-2].node->type != yyvsp[0].node->type) {
            cout << "\033[31mERROR\033[0m: type mismatch in division." << endl;
        }
        else if(yyvsp[0].node->ast->name == "0") {
            cout << "\033[31mERROR\033[0m: divide by zero error." << endl;
        }

        //pcout << "collect division\n";
    ;
    break;}
case 22:
#line 295 "./Source/grammar.y"
{
        yyval.node = new Node();
        yyval.node->ast = new ast_node("multiplicative_statement", 1, yyvsp[0].node->ast);

        if(yyvsp[0].node->type == DATA_TYPE::_VARIABLE) {
            if(table->find(yyvsp[0].node->ast->name)) {
                yyval.node->type = table->table[yyvsp[0].node->ast->name];
            }
            else {
                cout << "\033[31mERROR\033[0m: variable \"" << yyvsp[0].node->ast->name << "\" does not exist." << endl;
            }
        }

        //pcout << "collapse to multiplicative_statement\n";
    ;
    break;}
case 23:
#line 313 "./Source/grammar.y"
{
        yyval.node = yyvsp[-2].node;
        yyval.node->ast->addChildren(2, yyvsp[-1].node->ast, yyvsp[0].node->ast);

        // cout << $1->ast->name << "+" << $3->ast->name << endl;
        // cout << typeToString($1->type) << "+" << typeToString($3->type) << endl;
        if(yyvsp[-2].node->type != yyvsp[0].node->type) {
            cout << "\033[31mERROR\033[0m: type mismatch in addition." << endl;
        }

        //pcout << "collect addition\n";
    ;
    break;}
case 24:
#line 327 "./Source/grammar.y"
{
        yyval.node = yyvsp[-2].node;
        yyval.node->ast->addChildren(2, yyvsp[-1].node->ast, yyvsp[0].node->ast);

        if(yyvsp[-2].node->type != yyvsp[0].node->type) {
            cout << "\033[31mERROR\033[0m: type mismatch in subtraction." << endl;
        }

        //pcout << "collect subtraction\n";
    ;
    break;}
case 25:
#line 339 "./Source/grammar.y"
{
        yyval.node = new Node();
        yyval.node->ast = new ast_node("additive_statement", 1, yyvsp[0].node->ast);

        yyval.node->type = yyvsp[0].node->type;

        //pcout << "collapse to additive_statement\n";
    ;
    break;}
case 26:
#line 350 "./Source/grammar.y"
{
        yyval.node = new Node();
        yyval.node->ast = new ast_node("assignment_statement", 3, yyvsp[-2].node->ast, yyvsp[-1].node->ast, yyvsp[0].node->ast);
        
        // cout << $1->ast->name << "=" << $3->ast->name << endl;
        // cout << typeToString($1->type) << "=" << typeToString($3->type) << endl;
        if(yyvsp[-2].node->type != yyvsp[0].node->type) {
            cout << "\033[31mERROR\033[0m: type mismatch in assignment." << endl;
        }
        yyval.node->type = yyvsp[0].node->type;
        
        //pcout << "collapse to assignemnt_statement\n";
    ;
    break;}
case 27:
#line 365 "./Source/grammar.y"
{
        yyval.node = new Node();
        yyval.node->ast = new ast_node("assignment_statement", 3, yyvsp[-2].node->ast, yyvsp[-1].node->ast, yyvsp[0].node->ast);
        
        // cout << $1->ast->name << "=" << $3->ast->name << endl;
        // cout << typeToString($1->type) << "=" << typeToString($3->type) << endl;
        if(!table->find(yyvsp[-2].node->ast->name)) {
            cout << "\033[31mERROR\033[0m: this variable\"" << yyvsp[-2].node->ast->name << "\"does not exist." << endl;
        }
        else if(yyvsp[-2].node->type != yyvsp[0].node->type) {
            cout << "\033[31mERROR\033[0m: type mismatch in assignment." << endl;
        }
        yyval.node->type = yyvsp[0].node->type;

        //pcout << "collpase to assignement_statement\n";
    ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_toy_plus_plus_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_toy_plus_plus_DEBUG != 0
  if (YY_toy_plus_plus_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_toy_plus_plus_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_toy_plus_plus_LLOC.first_line;
      yylsp->first_column = YY_toy_plus_plus_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_toy_plus_plus_NERRS;

#ifdef YY_toy_plus_plus_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_toy_plus_plus_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_toy_plus_plus_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_toy_plus_plus_ERROR_VERBOSE */
	YY_toy_plus_plus_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_toy_plus_plus_CHAR == YYEOF)
	YYABORT;

#if YY_toy_plus_plus_DEBUG != 0
      if (YY_toy_plus_plus_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_toy_plus_plus_CHAR, yytname[yychar1]);
#endif

      YY_toy_plus_plus_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_toy_plus_plus_LSP_NEEDED
  yylsp--;
#endif

#if YY_toy_plus_plus_DEBUG != 0
  if (YY_toy_plus_plus_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_toy_plus_plus_DEBUG != 0
  if (YY_toy_plus_plus_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_toy_plus_plus_LVAL;
#ifdef YY_toy_plus_plus_LSP_NEEDED
  *++yylsp = YY_toy_plus_plus_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 382 "./Source/grammar.y"

/* ending grammar of the language */

/* describe yyerror function */
int yyerror(string s) {
    cout << "\x1B[31m" << "ERROR: " << "\033[0m" << s << endl;
    return 0;
}